# Generated by Django 2.1 on 2018-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180817_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielink',
            options={'ordering': ['episode_nr']},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movielink',
            name='episode_nr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
