# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180822_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.FloatField(default=0),
        ),
    ]
