# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180914_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_nr',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
