# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180918_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(db_index=True, max_length=70),
        ),
    ]
