# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('title_type', models.CharField(max_length=10)),
                ('is_adult', models.BooleanField(default=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('genres', models.CharField(max_length=30)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TitleAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=3)),
                ('original_title', models.BooleanField(default=False)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_data.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_data.Movie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_data.Name')),
            ],
        ),
        migrations.AddField(
            model_name='name',
            name='movies',
            field=models.ManyToManyField(related_name='names', through='imdb_data.TitlePrincipals', to='imdb_data.Movie'),
        ),
    ]
