# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='titlealias',
            name='original_title',
            field=models.NullBooleanField(default=False),
        ),
    ]
